name: animated_content
description: AnimatedContent package animates content transitions in Flutter apps with slide, fade, and combined animation types. Customize duration and styles to animate the entry and exit of child widgets.
version: 1.0.0
homepage: https://github.com/altaysakarya/animated_content
repository: https://github.com/altaysakarya/animated_content.git
documentation: https://github.com/altaysakarya/animated_content/blob/master/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

license: MIT